image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hugo
  - hut 
environment:
  site: meeknot.es
  wwwsite: www.meeknot.es
tasks:
  - package: |
      cd meeknot.es
      hugo
      tar -C public -cvz . > ../site.tar.gz
  - upload: | 
      hut pages publish -d $site site.tar.gz
      hut pages publish -d $wwwsite site.tar.gz


