baseURL = "ehawk61.github.io"
languageCode = "en-us"
theme = 'anatole'

[params]
title = "Meek Notes"
author = "Jonathan L. Meek"
description = "Call me Meek"
profilePicture = "images/profilePic.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jonathanlmeek/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ehawk61"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
